import './js/refs';
import './js/movies-api';
import './js/local-storage';
// import './js/movies-markup';
// import './js/search-movie';
// import './js/pagination';
import './js/modal';
import './js/footer-modal';
import './js/get-movie';
import './js/modal-trailer';
